# https://taskfile.dev

version: '3'

env:
  IMAGE_NAME: ghcr.io/cjcocokrisp/t1dash:dev

tasks:
  build:
    cmds:
      - npm run build:css
      - ./scripts/copy-embeds.sh
      - go build -o dist/t1dash ./cmd/

  docker-build:
    cmds:
      - docker build -t $IMAGE_NAME -f Containerfile .

  podman-build:
    cmds:
      - podman build -t $IMAGE_NAME .

  clean:
    cmds:
      - rm dist/t1dash internal/templates/web/static/style.css internal/db/setup-db.sh
      - rm -r internal/templates/web/
